
    drop table Account if exists;

    create table Account (
        id bigint generated by default as identity (start with 1),
        email varchar(255),
        password varchar(255),
        username varchar(255),
        version bigint,
        primary key (id)
    );
